version: "3.3"


services:

  mainnet-besu:
    container_name: mainnet-besu
    restart: "on-failure"
    image: hyperledger/besu:latest
    environment:
      BESU_GENESIS_FILE: /var/lib/besu/gen-besu.json
      BESU_DATA_PATH: /var/lib/besu
      BESU_HOST_ALLOWLIST: "*"
      BESU_RPC_WS_ENABLED: "true"
      BESU_RPC_WS_HOST: 0.0.0.0
      BESU_RPC_HTTP_HOST: 0.0.0.0
      BESU_RPC_HTTP_ENABLED: "true"
      BESU_RPC_HTTP_CORS_ORIGINS: "*"
      BESU_RPC_HTTP_API: "ETH,NET,WEB3,MINER"
      BESU_RPC_WS_API: "ETH,NET,WEB3,MINER"
      BESU_MINER_ENABLED: "true"
      BESU_MINER_COINBASE: fe3b557e8fb62b89f4916b721be55ceb828dbd73
    volumes:
      - $PWD/besu/besu-mainnet:/var/lib/besu
      - $PWD/besu/gen-besu.json:/var/lib/besu/gen-besu.json
    ports:
      - "9201:8545"
      - "9202:8546"
      - "9203:8547"
      - "9204:30303"

  mainnet-explorer:
    container_name: mainnet-explorer
    restart: "on-failure"
    image: alethio/ethereum-lite-explorer
    environment:
      APP_NODE_URL: "http://127.0.0.1:9201"
    ports:
      - 8081:80
    depends_on:
      - mainnet-besu
