services:

  besu:
    container_name: besu
    restart: "on-failure"
    image: hyperledger/besu:latest
    environment:
      BESU_GENESIS_FILE: /var/lib/besu/gen-besu.json
      BESU_DATA_PATH: /var/lib/besu
      BESU_HOST_ALLOWLIST: "*"
      BESU_RPC_WS_ENABLED: "true"
      BESU_RPC_WS_HOST: 0.0.0.0
      BESU_RPC_HTTP_HOST: 0.0.0.0
      BESU_RPC_HTTP_ENABLED: "true"
      BESU_RPC_HTTP_CORS_ORIGINS: "*"
      BESU_RPC_HTTP_API: "ADMIN,ETH,NET,WEB3,MINER,IBFT"
      BESU_RPC_WS_API: "ADMIN,ETH,NET,WEB3,MINER,IBFT"
      BESU_MINER_ENABLED: "true"
      BESU_MINER_COINBASE: fe3b557e8fb62b89f4916b721be55ceb828dbd73
    volumes:
      - ${BASE_PATH}/besu:/var/lib/besu
      - ${BASE_PATH}/gen-besu.json:/var/lib/besu/gen-besu.json
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
      - "30303:30303"

  explorer:
    container_name: explorer
    restart: "on-failure"
    image: alethio/ethereum-lite-explorer
    environment:
      APP_NODE_URL: "http://127.0.0.1:8545"
    ports:
      - 8080:80
    depends_on:
      - besu
