export const ETHERS_WS = Symbol("ETHERS_WS");
export const ETHERS_RPC = Symbol("ETHERS_RPC");
export const ETHERS_SIGNER = Symbol("ETHERS_SIGNER");
export const CONTRACT_OPTIONS_PROVIDER = Symbol("CONTRACT_OPTIONS_PROVIDER");
export const BLOCKCHAIN_OPTIONS_PROVIDER = Symbol("BLOCKCHAIN_OPTIONS_PROVIDER");
export const MODULE_OPTIONS_PROVIDER = Symbol("MODULE_OPTIONS_PROVIDER");
