name: Clean Packages

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Manual release Publish", "Manual release Publish --force"]
    types:
      - completed

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: clean old
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'nestjs-ethers'
          package-type: 'npm'
          min-versions-to-keep: 10
